group 'com.lykhonis.imagecrop'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 36
    namespace "com.lykhonis.imagecrop"

    defaultConfig {
        minSdkVersion 24
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lint {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'androidx.exifinterface:exifinterface:1.0.0'
}
